"""add_short_id_and_categories

Revision ID: 82c0b75b057e
Revises: 947b4977eb6c
Create Date: 2026-03-02 20:13:59.460556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c0b75b057e'
down_revision: Union[str, None] = '947b4977eb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clienti_short_id'), ['short_id'], unique=True)

    with op.batch_alter_table('documenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macro_categoria', sa.String(length=50), server_default='altro', nullable=False))
        batch_op.add_column(sa.Column('anno_competenza', sa.Integer(), nullable=True))

    # Removed problematic alter_column on users table for SQLite compatibility
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documenti', schema=None) as batch_op:
        batch_op.drop_column('anno_competenza')
        batch_op.drop_column('macro_categoria')

    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clienti_short_id'))
        batch_op.drop_column('short_id')
    # ### end Alembic commands ###