"""add_indexes_to_cliente_pi_cf

Revision ID: 8c2d1e3b896e
Revises: 70dc3fd11c4a
Create Date: 2026-03-02 16:45:08.318406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2d1e3b896e'
down_revision: Union[str, None] = '70dc3fd11c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Indexes ix_clienti_codice_fiscale and ix_clienti_partita_iva 
    # were already created in a previous partial run.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clienti_partita_iva'), table_name='clienti')
    op.drop_index(op.f('ix_clienti_codice_fiscale'), table_name='clienti')
    # ### end Alembic commands ###